# Generated by Django 4.2 on 2024-07-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego'), ('P', 'Planta'), ('E', 'Electrico')], max_length=30),
        ),
    ]
