# Generated by Django 5.0.7 on 2024-08-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('L', 'Lagartija'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego'), ('P', 'Planta')], max_length=30),
        ),
    ]
