# Generated by Django 5.0.7 on 2024-08-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('L', 'Lagartija'), ('P', 'Planta'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego')], max_length=30),
        ),
    ]
