# Generated by Django 4.2 on 2024-07-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('A', 'Agua'), ('L', 'Lagartija'), ('T', 'Tierra'), ('P', 'Planta'), ('F', 'Fuego')], max_length=30),
        ),
    ]
