# Generated by Django 5.0.7 on 2024-08-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('T', 'Tierra'), ('F', 'Fuego'), ('A', 'Agua'), ('L', 'Lagartija'), ('P', 'Planta')], max_length=30),
        ),
    ]
