# Generated by Django 5.0.7 on 2024-08-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('E', 'Eléctrico'), ('A', 'Agua'), ('T', 'Tierra'), ('F', 'Fuego'), ('P', 'Planta')], max_length=30),
        ),
    ]
