# Generated by Django 5.0.7 on 2024-08-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0009_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('P', 'Planta'), ('A', 'Agua'), ('L', 'Lagartija'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('F', 'Fuego')], max_length=30),
        ),
    ]
