# Generated by Django 5.0.7 on 2024-08-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0010_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('E', 'Eléctrico'), ('P', 'Planta'), ('L', 'Lagartija'), ('T', 'Tierra'), ('A', 'Agua'), ('F', 'Fuego')], max_length=30),
        ),
    ]
